import { todayISO, formatDate } from '../domain/schedule.js';
import { counts } from '../domain/workout.js';
import { esc,field,empty } from './shared.js';

export function recordsView(state) {
  const weights=state.weights.slice().sort((a,b)=>a.date.localeCompare(b.date)),records=state.workouts.filter(w=>w.status==='finished').slice().sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt);
  const days=new Set(records.filter(w=>counts(w).done>0 || w.summary.minutes>0).map(w=>w.date)).size;
  const mins=records.reduce((n,w)=>n+(w.summary.minutes||0),0),delta=weights.length>1?weights.at(-1).weight-weights[0].weight:null;
  const d=state.ui.weightDraft;
  return `<div class="page-heading"><div><p class="eyebrow">SMALL STEPS, REAL CHANGE</p><h1>나의 기록</h1></div></div><div class="stats-grid"><div><b>${days}<small>일</small></b><span>운동한 날</span></div><div><b>${mins.toLocaleString()}<small>분</small></b><span>실제 운동</span></div><div><b>${delta===null?'—':(delta>0?'+':'')+delta.toFixed(1)}<small>kg</small></b><span>체중 변화</span></div></div>
    <section class="card"><div class="section-title"><h2>체중 기록</h2><span class="muted small">목표 ${state.settings.targetWeight} kg</span></div><form id="weightForm"><div class="form-grid">${field('날짜','date',d.date||todayISO(),{type:'date',required:true})}${field('체중 · kg','weight',d.weight??'',{min:40,max:250,step:0.1,required:true,placeholder:weights.at(-1)?.weight.toFixed(1)||'예: 110.0'})}</div><details class="details"><summary>허리둘레·수면 <span>선택</span></summary><div class="form-grid">${field('허리둘레 · cm','waist',d.waist??'',{min:40,max:250,step:0.1})}${field('수면 · 시간','sleep',d.sleep??'',{min:0,max:24,step:0.5})}</div></details><button class="secondary" type="submit">체중 저장</button></form>${weightChart(weights,state.settings.targetWeight)}${weights.length?`<details class="details"><summary>체중 기록 ${weights.length}개 보기</summary><div class="weight-history">${weights.slice().reverse().map(w=>`<div class="history-line"><span><b>${w.weight.toFixed(1)} kg</b><small>${esc(w.date)}${w.waist!==null&&w.waist!==undefined?' · 허리 '+w.waist+'cm':''}${w.sleep!==null&&w.sleep!==undefined?' · 수면 '+w.sleep+'시간':''}</small></span><button class="text-button danger-text" type="button" data-action="delete-weight" data-date="${esc(w.date)}">삭제</button></div>`).join('')}</div></details>`:''}</section>
    <section class="history-section"><div class="section-title"><h2>운동 이력</h2><span class="muted small">${records.length}개 기록</span></div>${records.length?records.map(w=>{const c=counts(w);return `<details class="history-card"><summary><div><span class="muted small">${formatDate(w.date)}${w.legacy?' · 이전 기록':''}</span><b>${esc(w.title)}</b><span class="muted small">${c.total?`${c.done}/${c.total}종목 · `:''}${w.summary.minutes===null?'시간 미기록':w.summary.minutes+'분'}${w.summary.distance!==null?' · '+w.summary.distance+'km':''}</span></div><span class="expand-mark">＋</span></summary><div class="history-detail">${w.legacy?'<p class="muted small">기존 체크 기록의 날짜는 당시 프로그램 시작일을 기준으로 옮겼어요.</p>':''}${w.tasks.map(t=>`<div class="history-line"><span>${esc(t.name)}<small>${t.status==='done'?'완료':t.status==='skipped'?'건너뜀':'미완료'}</small></span><span>${t.weight!==null?esc(t.weight)+' kg':''}${t.rpe!==null?' · RPE '+t.rpe:''}</span></div>`).join('')}${w.summary.rpe!==null?`<p>체감 강도: ${w.summary.rpe}/10</p>`:''}${w.summary.pain?`<p>관절 상태: ${esc(w.summary.pain)}</p>`:''}${w.summary.memo?`<p class="memo">${esc(w.summary.memo)}</p>`:''}</div></details>`;}).join(''):empty('첫 운동을 기다리고 있어요','운동을 마치면 여기에 기록이 쌓여요.')}</section>`;
}

function weightChart(weights,target) {
  if(!weights.length) return empty('체중 변화가 여기에 보여요','첫 체중을 기록해 주세요.');
  const values=weights.map(w=>w.weight),min=Math.min(...values,target)-1,max=Math.max(...values,target)+1;
  const times=weights.map(w=>+new Date(w.date+'T12:00:00')),span=times.at(-1)-times[0];
  const X=i=>span?40+(times[i]-times[0])/span*288:184,Y=v=>18+(max-v)/(max-min)*128;
  const ticks=[0,.5,1].map(q=>{const v=max-(max-min)*q,y=Y(v);return `<line x1="40" x2="328" y1="${y}" y2="${y}" class="grid"/><text x="0" y="${y+4}">${v.toFixed(1)}</text>`;}).join('');
  return `<svg class="chart" viewBox="0 0 360 184" role="img" aria-label="체중 추이: ${weights[0].date} ${weights[0].weight}kg에서 ${weights.at(-1).date} ${weights.at(-1).weight}kg"><line class="goal-line" x1="40" x2="328" y1="${Y(target)}" y2="${Y(target)}"/>${ticks}<polyline points="${weights.map((w,i)=>`${X(i)},${Y(w.weight)}`).join(' ')}" class="chart-line"/>${weights.map((w,i)=>`<circle cx="${X(i)}" cy="${Y(w.weight)}" r="3.5" class="chart-dot"/>`).join('')}<text x="40" y="176">${weights[0].date.slice(5)}</text><text x="328" y="176" text-anchor="end">${weights.at(-1).date.slice(5)}</text></svg>`;
}
